/*
 * Generated by erpcgen 1.10.0 on Sun May 28 16:55:50 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_bbcar_control_h_)
#define _bbcar_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief BBCarService identifiers */
enum _BBCarService_ids
{
    kBBCarService_service_id = 1,
    kBBCarService_stop_id = 1,
    kBBCarService_goStraight_id = 2,
    kBBCarService_turn_id = 3,
    kBBCarService_spin_id = 4,
    kBBCarService_start_id = 5,
    kBBCarService_getDistance_id = 6,
    kBBCarService_getSpeed_id = 7,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name BBCarService
//@{
void stop(void);

void goStraight(int32_t speed);

void turn(int32_t speed, double factor);

void spin(int32_t speed);

void start(void);

double getDistance(void);

double getSpeed(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _bbcar_control_h_
